name: valbury
version: 1.0.0+1
publish_to: none
description: Valbury
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  # State Management
  get: 4.6.5

  # Services
  shared_preferences: ^2.0.20
  encrypt: ^5.0.1
  get_it: ^7.3.0
  intl: ^0.17.0
  fluttertoast: ^8.2.1

  # User Interface
  cupertino_icons: ^1.0.2
  pull_to_refresh: ^2.0.0
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  lottie: ^2.3.2
  awesome_dialog: ^3.0.2

  # Firebase
  firebase_core: ^2.8.0
  firebase_remote_config: ^4.0.2
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_analytics: ^10.2.1

  flutter:
    sdk: flutter

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/lotties/empty/

